In [ ]:
from pytz import timezone

from datetime import datetime
today = datetime.now(timezone('Asia/Seoul'))
print("{}-{}-{}".format(datetime.today().year, str(datetime.today().month).zfill(2), datetime.today().day))

2022-06-21


In [ ]:
#2530번

h, m, s = map(int, input().split())
p = int(input())

s=s+p
m=m+s//60
h=h+m//60

print("{} {} {}".format(h%24, m%60, s%60))

17 40 45
6015
19 21 0


In [ ]:
n, m = map(int, input().split())

memo={0:1, 1:1}
def fac(n):
    if n in memo:
        return memo[n]
    else :
        output = fac(n-1)*n
        memo[n]= output
        return output
    
nlist=[[i] for i in range(1,n+1)]*fac(m-1)
count=0
while count<m:
    count+=1
    for i in range(1,n+1):
        for x in nlist:
            if i not in x:
                x.append(i)
            
for i in sorted(nlist):
    print(" ".join(list(map(str, i))))

4 3
1 2 3 4
1 2 3 4
2 1 3 4
2 1 3 4
3 1 2 4
3 1 2 4
4 1 2 3
4 1 2 3


In [ ]:
#2108번

n=int(input())

numlist=[int(input()) for _ in range(n)]
numdic={i:0 for i in sorted(set(numlist))}
numscore = [0 for i in range(n)]

for i in numlist:
    numdic[i]+=1

for i in range(len(numdic)):
  numscore[i]+=numdic[list(numdic.keys())[i]]


print(round(float(sum(numlist))/n))
print(sorted(numlist)[(n-1)//2])
if numscore.count(max(numscore))==1:
  print(list(numdic.keys())[numscore.index(max(numscore))])

else :
  numdic[list(numdic.keys())[numscore.index(max(numscore))]]-=1
  numscore[numscore.index(max(numscore))]-=1
  print(list(numdic.keys())[numscore.index(max(numscore))])

print(max(numlist)-min(numlist))

5
1
3
8
-2
2
2
2
1
10


In [ ]:
#2108번

n=int(input())

numlist=[int(input()) for _ in range(n)]
numdic={i:0 for i in sorted(set(numlist))}
answer=[]

for i in numlist:
    numdic[i]+=1
numscore = max(list(numdic.values()))
for i in numdic:
  if numdic[i]==numscore:
    answer.append(i)
# print(numdic)
# print(answer)


print(round(float(sum(numlist))/n))
print(sorted(numlist)[(n-1)//2])
if len(answer)==1:
  print(answer[0])
else:
  print(answer[1])
print(max(numlist)-min(numlist))

5
1
3
8
-2
2
{-2: 1, 1: 1, 2: 1, 3: 1, 8: 1}
[-2, 1, 2, 3, 8]
2
2
1
10


In [ ]:
x={1:2, 2:5}
print(list(x.values()))

y=[3,4,2,4]
print(y.index(max(y)))
del y[y.index(max(y))]
print(y.index(max(y)))

print(y)

[2, 5]
1
2
[3, 2, 4]


In [ ]:
print("".join(map(str,sorted(map(int, list(input())), reverse=True))))

2143
4321


In [ ]:
#11650번

n=int(input())

numlist = [input().split()  for _ in range(n)]

num_list=[[int(x),int(y)] for x,y in numlist]
answer=sorted(num_list, key=lambda b: [b[0], b[1]])
for x, y in answer:
  print("{} {}".format(x,y))

5
3 4
1 1
1 -1
2 2
3 3
1 -1
1 1
2 2
3 3
3 4


In [ ]:
n=int(input())

wordlist=[input() for _ in range(n)]
lenandword=[[len(i), i] for i in wordlist]
answer=sorted(lenandword, key=lambda b: [b[0], b[1]])

for word in answer:
  print(word[1])

5
but
i
it
im
no
i
im
it
no
but


In [ ]:
print(answer)
answer2=sorted(wordlist, key= lambda x: [len(x), x])
print(answer2)

[[1, 'i'], [2, 'im'], [2, 'it'], [2, 'no'], [3, 'but']]
['i', 'im', 'it', 'no', 'but']


In [ ]:
n= int(input())
age_and_idlist=[input().split()+[i] for i in range(n)]

answer = sorted(age_and_idlist, key=lambda x : [x[0], x[2]])


4
19 KD
15 AD
16 DA
15 AC
15 AD
15 AC
16 DA
19 KD


In [ ]:

for i in answer:
  print("{} {}".format(i[0],i[1]))

15 AD
15 AC
16 DA
19 KD


In [ ]:
import numpy as np

timesteps = 10
input_dim = 4
hidden_units = 8

# 입력에 해당되는 2D 텐서
inputs = np.random.random((timesteps, input_dim))

# 초기 은닉 상태는 0(벡터)로 초기화
hidden_state_t = np.zeros((hidden_units,)) 

print('초기 은닉 상태 :',hidden_state_t)
print('input:',inputs)

초기 은닉 상태 : [0. 0. 0. 0. 0. 0. 0. 0.]
input: [[0.92327021 0.36171303 0.4342065  0.00485571]
 [0.94574232 0.38960725 0.16964259 0.59434058]
 [0.07577052 0.48598928 0.49908345 0.54819251]
 [0.30903108 0.48341621 0.35951342 0.11707694]
 [0.4674206  0.43430768 0.06548439 0.8547116 ]
 [0.64124664 0.09777214 0.17448987 0.56201394]
 [0.73446414 0.94430254 0.22264656 0.35910915]
 [0.17647215 0.92072716 0.28495447 0.22902299]
 [0.52495891 0.4301569  0.16670577 0.52902408]
 [0.84322626 0.85683852 0.36144096 0.39616257]]


In [ ]:
Wx = np.random.random((hidden_units, input_dim))  # (8, 4)크기의 2D 텐서 생성. 입력에 대한 가중치.
Wh = np.random.random((hidden_units, hidden_units)) # (8, 8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치.
b = np.random.random((hidden_units,)) # (8,)크기의 1D 텐서 생성. 이 값은 편향(bias).

# of params = (Dh * Dh)       +     (Dh * d)      +   (Dh)
#               (Wh)   *ht-1  +     (Wx)    * xt  +   (b)

print('가중치 Wx의 크기(shape) :',np.shape(Wx))
print('가중치 Wh의 크기(shape) :',np.shape(Wh))
print('편향의 크기(shape) :',np.shape(b))


가중치 Wx의 크기(shape) : (8, 4)
가중치 Wh의 크기(shape) : (8, 8)
편향의 크기(shape) : (8,)


In [ ]:
print(Wx)

[[0.45799203 0.96580596 0.34739782 0.50183672]
 [0.33144343 0.50306213 0.45111617 0.37539951]
 [0.34959072 0.38110424 0.19433192 0.67219421]
 [0.22594931 0.99526381 0.45786526 0.1741255 ]
 [0.60114357 0.18871761 0.49526342 0.93600498]
 [0.79485204 0.28655797 0.01514563 0.89185278]
 [0.72314854 0.53195321 0.33442802 0.27106337]
 [0.50379579 0.56794504 0.71470423 0.50108934]]


In [ ]:
total_hidden_states = []

# 각 시점 별 입력값.
for input_t in inputs:

  # Wx * Xt + Wh * Ht-1 + b(bias)
  output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t) + b)

  # 각 시점 t별 메모리 셀의 출력의 크기는 (timestep t, output_dim)
  # 각 시점의 은닉 상태의 값을 계속해서 누적
  total_hidden_states.append(list(output_t))
  hidden_state_t = output_t

# 출력 시 값을 깔끔하게 해주는 용도.
total_hidden_states = np.stack(total_hidden_states, axis = 0) 

# (timesteps, output_dim)
print('모든 시점의 은닉 상태 :')
print(total_hidden_states)

모든 시점의 은닉 상태 :
[[0.8461114  0.75284881 0.6330158  0.90467936 0.73954435 0.8274086
  0.84587861 0.95731045]
 [0.99996218 0.99955511 0.99939435 0.99997582 0.9988057  0.999876
  0.99986011 0.99992778]
 [0.99999309 0.99989321 0.99976976 0.99999499 0.99897953 0.99987686
  0.99990621 0.99997975]
 [0.99999049 0.99985637 0.999631   0.99999403 0.99801561 0.99981577
  0.99990701 0.99996985]
 [0.9999947  0.99989812 0.99985723 0.99999379 0.99943723 0.99996009
  0.99993637 0.99998022]
 [0.99998926 0.99985633 0.99976825 0.99998876 0.99919588 0.9999384
  0.99992294 0.99997213]
 [0.99999772 0.99993572 0.9998531  0.99999795 0.99927183 0.9999531
  0.99997042 0.9999889 ]
 [0.99999566 0.99990072 0.99974324 0.99999727 0.99827763 0.99985475
  0.99993005 0.99997916]
 [0.99999345 0.99988527 0.99979517 0.99999377 0.99912494 0.99993496
  0.99993445 0.99997752]
 [0.99999786 0.99994396 0.99986882 0.99999798 0.99946298 0.99996133
  0.99997522 0.99999132]]


In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Embedding, Dense

vocab_size = 2000
embedding_dim = 100
hidden_size = 64

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_size, batch_input_shape=(30, 3, 2000),return_sequences=True))
model.add(Dense(1, activation='sigmoid'))
model.summary() 

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, None, 100)         200000    
                                                                 
 simple_rnn_7 (SimpleRNN)    (None, None, 64)          10560     
                                                                 
 dense_6 (Dense)             (None, None, 1)           65        
                                                                 
Total params: 210,625
Trainable params: 210,625
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Embedding, Dense

vocab_size = 2000
embedding_dim = 100
hidden_size = 64

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_size, return_sequences=True))
model.add(Dense(1, activation='sigmoid'))
model.summary() 

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 100)         200000    
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, None, 64)          10560     
                                                                 
 dense_2 (Dense)             (None, None, 1)           65        
                                                                 
Total params: 210,625
Trainable params: 210,625
Non-trainable params: 0
_________________________________________________________________


In [ ]:
n= int(input())
age_and_idlist=[input().rstrip().split()+[i] for i in range(n)]

answer = sorted(age_and_idlist, key=lambda x : [int(x[0]), x[2]])

for i in answer:
  print("{} {}".format(int(i[0]),i[1]))

In [ ]:
n=int(input())
numlist=list(map(int, input().split()))

sort_num=sorted(set(numlist))
num_dic={sort_num[i]:i for i in range(len(sort_num))}

  print(num_dic[i], end=" ")


5
2 4 -10 4 -9
2 3 0 3 1 

In [ ]:
print(d)
print(num_newdic)
print(num_dic)

deque([])
{-10: 1, -9: 2, 2: 3, 4: 5}
{-10: 1, -9: 1, 2: 1, 4: 2}


In [ ]:
print(num_dic)

{-10: 1, -9: 1, 2: 1, 4: 2}


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)


lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

(1, 4, 5)
hidden state : [[0.11914973 0.3530825  0.00376497]], shape: (1, 3)
last hidden state : [[0.11914973 0.3530825  0.00376497]], shape: (1, 3)
last cell state : [[0.3622366  0.6442737  0.02801314]], shape: (1, 3)


In [ ]:
from collections import deque

M=int(input())
my_card=deque(map(int, input().split()))

N=int(input())
check_card=deque(map(int, input().split()))

for i in check_card:
  if i in my_card:
    print(1,end=" ")
  else :
    print(0, end=" ")

5
6 3 2 10 -10
8
10 9 -5 2 3 4 5 -10
1 0
0
1 1 0
0
1 

In [ ]:
n, m = map(int, input().split())

lset=set([input() for _ in range(n)])
mset=set([input() for _ in range(m)])

lmset= lset.intersection(mset)

print(len(lmset))
if len(lmset)!=0:
  for i in sorted(lmset):
      print(i)

In [ ]:
x=set(["a","d","c","s"])
print(sorted(x))

['a', 'c', 'd', 's']


In [ ]:
from itertools import permutations

n, m = map(int, input().split())
for x in list(permutations([i for i in range(1, n+1)], m)):
  print(*x)

4 3
1 2 3
1 2 4
1 3 2
1 3 4
1 4 2
1 4 3
2 1 3
2 1 4
2 3 1
2 3 4
2 4 1
2 4 3
3 1 2
3 1 4
3 2 1
3 2 4
3 4 1
3 4 2
4 1 2
4 1 3
4 2 1
4 2 3
4 3 1
4 3 2


In [ ]:
import sys

n= int(input())
se_time_list = [list(map(int, input().split())) for _ in range(n)]




# print("stlist1:",stlist1)
# print("stlist2:",stlist2)
# print("stdic:",stdic)
# print("now값:",now)
# print("count값:",count)

11
1 4
3 5
0 6
5 7
3 8
5 9
6 10
8 11
8 12
2 13
12 14


In [ ]:
stlist1 = sorted(se_time_list, key= lambda fir : fir[1], reverse=True)
stlist2 = [[-1, -1]]
sedic = {}

for i in range(len(stlist1)):
  p, q = stlist1[i] 
  if p >= stlist2[-1][1] and p<2**(31) and q<2**(31):
    stlist2.append(stlist1[i])

print(len(stlist2)-1)


1


In [ ]:
import sys

n= int(input())
se_time_list = [list(map(int, input().split())) for _ in range(n)]

stlist1 = sorted(se_time_list, key= lambda fir : (fir[1],fir[0]), reverse=True)
stlist2 = [[-1, -1]]
sedic = {}
count=0

for s, e in stlist1:
  if s==e:
    count+=1
  sedic[s]=e
# print(sedic)

from collections import deque
d= deque([[-1,-1]])
for s, e in list(sedic.items())[::-1]:

  if s>=d[-1][1]:
    d.append([s, e])

print(len(d)-1+count)

{12: 14, 2: 13, 8: 11, 6: 10, 5: 7, 3: 5, 0: 6, 1: 4}
1 4
0 6
3 5
5 7
6 10
8 11
2 13
12 14


In [ ]:
n=int(input())
se_time_list = [list(map(int, input().split())) for _ in range(n)]

11
1 4
3 5
0 6
5 7
3 8
5 9
6 10
8 11
8 12
2 13
12 14


0

In [ ]:
s, e = map(int, input().split())

priorlist={2:0, 3:0}

def prior(n):
  if n in priorlist:
    return True
  else :
    for i in list(priorlist.keys()):
      if n%i==0:
        return False
        break
    priorlist[n]=0
    return True

prior(e)

for i in list(priorlist.keys()):
  print(i)

3 16
2
3


In [ ]:


print(*priorlist.keys(), end="\n")

2 3 5 7 11 13


In [ ]:
print(priorlist)

{2: 0, 3: 0, 11: 0}


In [ ]:
sortlist = sorted(se_time_list, key= lambda x: [x[1],x[0]])
print(sortlist)
answer=[sortlist[0]]
print(answer)
count=1

for i in sortlist:
  p=i[0]
  q=i[1]
  if p==q:
    count+=1
  elif p>=answer[-1][1]:
    answer.append([p,q])
    count+=1
print(count)

[[1, 4], [3, 5], [0, 6], [5, 7], [3, 8], [5, 9], [6, 10], [8, 11], [8, 12], [2, 13], [12, 14]]
[[1, 4]]
4


In [ ]:
for i in sortlist:
  p=i[0]
  q=i[1]
  if p==q:
    count+=1
  elif p>=answer[-1][1]:
    answer.append([p,q])
    count+=1
print(count-1)

-1


In [ ]:
import sys

N = int(sys.stdin.readline())

time = [[0]*2 for _ in range(N)]
for i in range(N):
    s, e = map(int, sys.stdin.readline().split())
    time[i][0] = s
    time[i][1] = e

time.sort(key = lambda x: (x[1], x[0]))

cnt = 1
end_time = time[0][1]
for i in range(1, N):
    if time[i][0] >= end_time:
        cnt += 1
        end_time = time[i][1]

print(cnt)


In [ ]:
print(answer)

[[-1, -1], [1, 4], [5, 7], [8, 11], [12, 14]]


In [ ]:
from collections import deque
d= deque([[-1,-1]])
for s, e in list(sedic.items())[::-1]:

  if s>=d[-1][1]:
    d.append([s, e])

print(len(d)-1)

4


In [ ]:
n=int(input())

for _ in range(n):
    x= int(input()) # 합이 x가 되도록
    if x%2==0:
        answer=["{} {}".format(i, x-i) for i in range(1,x//2+1) if i!=x-i]
    else :
        answer=["{} {}".format(i, x-i) for i in range(1, (x-1)//2+1) if i!=x-i]
    
    print("Pairs for {}: {}".format(x, ", ".join(answer)))

1
2
Pairs for 2: 


In [ ]:
from collections import deque

n= int(input())
k= int(input())

numlist=sorted(list(set(map(int, input().split()))))

distance=sorted([numlist[i+1]-numlist[i] for i in range(len(numlist)-1)])
dd = deque(distance)

if k!=1:
    for _ in range(k-1):
        dd.pop()
    print(sum(list(dd)))
else:
    print(sum(distance))
    

1
1
3
0


In [ ]:
from collections import deque

n= int(input())
k= int(input())

numlist=sorted(list(set(int, input().split())))

if n==1 or k==1:
  print(sum(numlist))

elif k>=len(numlist):
  print(0)

elif k<len(numlist):
    distance=sorted([numlist[i+1]-numlist[i] for i in range(len(numlist)-1)])
    dd = deque(distance)
    for _ in range(k-1):
        dd.pop()
    print(sum(list(dd)))

6
2
1 6 9 3 6 7
5


In [ ]:
from collections import deque

n = int(input())
k = int(input())
num = sorted(list(map(int, input().split())))

if k >= n:
    print(0)

else:
  dist = []
  for i in range(1, n):
     dist.append(num[i] - num[i-1])

  answer = deque(sorted(dist,reverse=True))
  for _ in range(k-1):
      answer.popleft()

  print(sum(list(answer)))

6
2
1 6 9 3 6 7
5


In [ ]:
n=int(input())

info=[list(map(int,input().split())) for _ in range(n)]

d, o = map(int, input().split())

4
4 4
5 2
11 5
15 10
25 10


In [ ]:
print(info)


from collections import deque
#s가 o보다 클때

#s가 o보다 작거나 같을때

if s<=o:
  print(0)

elif s>o:
  if len(befo)==0: #기름을 아에 넣을 수 없을 때
    print(-1)
  
  else:
    for st, ot in info:
        
        break

    elif 

[[4, 4], [5, 2], [11, 5], [15, 10]]


In [ ]:
befo=sorted([i for i in info if i[0]<=o], key= lambda x:x[0])

aft =[i for i in info if i[0]>o]


print(befo)
print(aft) 

[[4, 4], [5, 2]]
[[11, 5], [15, 10]]


In [ ]:
print(numlist)
print(distance)
print(dd)

[3, 6, 7, 8, 10, 12, 14, 15, 18, 20]
[1, 1, 1, 2, 2, 2, 2, 3, 3]
deque([])


In [ ]:
print(distance)

[]


In [ ]:
if input()==input():
    print(1)
else:
    print(0)

1
1
1


In [ ]:
from collections import deque

n= int(input())
k= int(input())

numlist=sorted(list(set(map(int, input().split()))))

if n!=1:
    distance=sorted([numlist[i+1]-numlist[i] for i in range(len(numlist)-1)])
    dd = deque(distance)

else:
    distance=numlist
    
if k!=1:
    for _ in range(k-1):
        dd.pop()
    print(sum(list(dd)))
else:
    print(sum(distance))
    

6
2
1 6 9 3 6 7
5


In [ ]:
answer

['1 6', '2 5', '3 4']

In [ ]:
import sys
n= int(input())
n_list = input().split()
n_set = set(n_list)

m= int(input())
m_list = input().split()

answer=[]

ndic={i:0 for i in n_set}
for i in n_list:
    ndic[i]+=1
 
for i in m_list:
    if i in ndic:
        print(ndic[i], end=" ")
    else :
        print(0, end=" ")

10
6 3 2 10 10 10 -10 -10 7 3
8
10 9 -5 2 3 4 5 -10
3 0
0
1 2 0
0
2 

In [ ]:
import math
from math import pi

x1, y1, r1, x2, y2, r2 = map(float, input().split())

def answer(x1, y1, r1, x2, y2, r2):
  A=2*(x1-x2)
  B=2*(y1-y2)
  C=(x2**2+y2**2-r2**2-x1**2-y1**2+r1**2)

  l1=(abs(A*x1+B*y1+C))/math.sqrt((math.pow(A,2)+math.pow(B,2)))
  l2=(abs(A*x2+B*y2+C))/math.sqrt((math.pow(A,2)+math.pow(B,2)))

  ang1 = math.acos(l1/r1)*2
  ang2 = math.acos(l2/r2)*2

  s1=(r1**2)*math.pi*(math.degrees(ang1)/360)+(r2**2)*math.pi*(math.degrees(ang2)/360)
  s2=((r1**2)*math.sin(ang1)+(r2**2)*math.sin(ang2))/2

  return round(s1-s2,3)

print(answer(x1,y1,r1,x2,y2,r2))

20.0 30.0 15.0 40.0 30.0 30.0
210.801


In [ ]:
import math
from math import pi

x1, y1, r1, x2, y2, r2 = map(float, input().split())


A=2*(x1-x2)
B=2*(y1-y2)
C=(x2**2+y2**2-r2**2-x1**2-y1**2+r1**2)

l1=(abs(A*x1+B*y1+C))/math.sqrt(A**2+B**2)
l2=(abs(A*x2+B*y2+C))/math.sqrt(A**2+B**2)

ang1 = math.acos(l1/r1)*2
ang2 = math.acos(l2/r2)*2

s1=(r1**2)*math.pi*(math.degrees(ang1)/360)+(r2**2)*math.pi*(math.degrees(ang2)/360)
s2=((r1**2)*math.sin(ang1)+(r2**2)*math.sin(ang2))/2



20.0 30.0 15.0 40.0 30.0 30.0


In [ ]:
print(round(r2**2*math.pi-(s1-s2),3))
print(ang1)
print(math.degrees(ang1)/360)
math.degrees(2*math.pi)
print(s1-s2)
s3=r1*(l1+l2)*math.sin(ang1/2)
print(s3)
s1-s3

2616.632
2.1893545317662007
0.34844659591123284
210.80140237064654
449.9450650062044


210.80140237064649

In [ ]:
print(ang2)

0.9209868501181186


In [ ]:
print((8/3)*math.pi-2*math.sqrt(3))

4.913478794435027


In [ ]:
s1-s2

210.80140237064654

In [ ]:
print(s2)
print(math.sqrt((x1-x2)**2+(y1-y2)**2)*r2*math.sin(ang2/2))
print((l1+l2)*r2*math.sin(ang2/2))
print(s1)

449.94506500620435
266.63411259626923
449.9450650062043
660.7464673768509


In [ ]:
import math

x0, y0, r0, x1, y1, r1 = map(float, input().split())


def area(x0, y0, r0, x1, y1, r1):
    d = math.sqrt((x0 - x1) ** 2 + (y0 - y1) ** 2)
    rr0 = r0 * r0
    rr1 = r1 * r1
    # Circles do not overlap
    if (d > r1 + r0):
        return 0
    # Circle1 is completely inside circle0
    elif (d <= abs(r0 - r1) and r0 >= r1):
        return math.pi * rr1
    # Circle0 is completely inside circle1
    elif (d <= abs(r0 - r1) and r0 < r1):
        # Return area of circle0
        return math.pi * rr0
    # Circles partially overlap
    else:
        phi = (math.acos((rr0 + (d * d) - rr1) / (2 * r0 * d))) * 2
        theta = (math.acos((rr1 + (d * d) - rr0) / (2 * r1 * d))) * 2
        area1 = 0.5 * theta * rr1 - 0.5 * rr1 * math.sin(theta)
        area2 = 0.5 * phi * rr0 - 0.5 * rr0 * math.sin(phi)

        # Return area of intersection
        return area1 + area2


answer = float(round(1000 * area(x0, y0, r0, x1, y1, r1)) / 1000)
print('%.3f' % answer)

20.0 30.0 15.0 40.0 30.0 30.0
608.366
